### ISSUE TITLE
AgentSetup

### ISSUE THREAD

**Issue by MLiONS** [VajraSecurity/vajra-client#1]
1. Window 7 only support TLS 1.0 by default. Downloading Osquery logs from Gitbub may not be possible as Github needs TLSv1.2.
2. We decided to keep the Osquery binaries locally. 
3. Study configure file from EclecticIQ. There should be separate packs for 32-bit and 64-bit machines.

@sablearjun

**Comment by MLiONS** [comment]
Use batch files instead of PowerShell.

You don't need to copy files from the USB drive to the local drive.
The batch file should handle the installation. 

Offline installation using a batch file
Online installtion using a PowerShell. 

Powershell may be disabled on Windows 7. 

We decided to go with complete offline installation for all Windows versions and use only batch files for installation. 

@sablearjun

**Comment by sablearjun** [comment]
> 1. Window 7 only support TLS 1.0 by default. Downloading Osquery logs from Gitbub may not be possible as Github needs TLSv1.2.
> 2. We decided to keep the Osquery binaries locally.
> 3. Study configure file from EclecticIQ. There should be separate packs for 32-bit and 64-bit machines.
> 
> @sablearjun


As windows 7 only supports TLS1.0, so it is not always possible to download files, so we are keeping all files offline in a folder. From there script will copy all files.

**Comment by sablearjun** [comment]
All the tasks assigned are completed, pushed and raised PR #4
