### ISSUE TITLE
Improvements to client installer batch file for Windows

### ISSUE THREAD

**Issue by yogioncloud** [VajraSecurity/vajra-client#3]
1. Check that it is running on a supported OS (i.e. Win7 and above). If not, then throw the appropriate error message. Here are some examples on how it can be achieved: https://stackoverflow.com/questions/13212033/get-windows-version-in-a-batch-file

2. Check that the script has administrator privilege. If not, then throw the appropriate error message. Here are some examples on how it is achieved. (https://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights#21295806)

I would recommend adding a "InstallVajra_Readme.txt" file that has date and year of publication, ownership header of IIT Bombay, attributions to other products (like osquery) and describes what the solution is and an email address to contact for any issues. 

The similar text should also be visible on the screen and then take a user prompt to say 'Press [y|Y] to continue. Any other key to exit'

The prompt can be disabled for advanced users that can invoke the script with a '-silent' command line parameter.

3. At the top-most level, minimize the number of files visible to the user. Just have 4 things in the top most layer
a) batch file
b) readme (as mentioned above)
c) 2 folders; one named 'x86_32' and other named 'x86_64'
d) one folder named 'common'

Move all the CPU specific files to their respective folders and the shared/common files to 'common' folder. These become the source folders for respective destination

4. Error checking: At every stage you are invoking any system command (copy, sc etc) after that you need to check %ErrorLevel% and if it is not success, log it into an output file and exit from the script. The users can be asked to share the output file so we can identify at which stage something didn't work and why.

5. At the end of the who script, do an additional validation that all the files have reached where they were supposed to, services are running as expected and finally display a message "vajra client successfully installed".

**Comment by MLiONS** [comment]
--- Add ACL code to change the privileges of installed files to ensure clean delete in all code.
-- Add proper indentation
-- Check the error handling at all points. 
@sablearjun

**Comment by MLiONS** [comment]
Update the code for clear exit

@yogioncloud @sablearjun

**Comment by sablearjun** [comment]
All the requirements are satisfied in latest build. So closing the issue.
